version: "1.0"
info:
  model: int-scaffold
packages:
- name: Auto_ScaffoldingTestProject
  gitServerName: GitTokenExpiry9thNov
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.auto_scaffoldingtest.integrations:test
  packages:
  - name: Auto_ScaffoldingTestProject
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.2016
