version: "1.0"
info:
  model: int-scaffold
packages:
- name: Auto_ScaffoldingTestProject
  gitServerName: GitTokenExpiry9thNov
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
